### ISSUE TITLE
BED6 throws an error

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio.prioritize#1]
When using 6-column BED format for the known regions instead of 4-column format we get a java.lang.NumberFormatException in known.clj line 66. It would be helpful if the implementation would accept all BED files with at least 4 columns. In that manner BED files used for other purposes in bcbio could be re-used here without issue.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for the report. You're right that there was an implicit assumption that inputs are BED inputs are 4-column. I updated bcbio.prioritize and pushed a new version to bcbio that I hope will fix this. I couldn't replicate your exact problem but hope this resolves it for you. Thanks again

**Comment by schelhorn** [comment]
Great, thank you.
